language: node_js
node_js: node
services:
  - mongodb
before_deploy:
  - node public/build
  - git add public/dist/ --force
  - git commit -m "Updating build."
  - donejs deploy
deploy:
  skip_cleanup: true
  provider: heroku
  app: pacific-crag-24804
  api_key:
    - secure: j3PmnzBbKGA9+5vbU+NeYcYUqXYR0LVGHxP2Ct3TEMPxlULTvREw612/5XN0CHAUFWoPEtFHehXXkli28V0vZT1XgVlFmYru5EFOjMOtMVacQfbhoddHybda2U9XiRBez9s0YH963Fc47L/ecfe5pPDjIekiU+CjQJ4CQ5L1QYR7W93/TFc29WGdPnv6VbJICAsLkWiWBuoNWpL5zmlFxIa8LLdsAadQN7mT+2rpXMXGdDpeCvYVWTKgvNAiMtzTagrfV9K+pHgFALnEGe905SpzENLShn8SBZDz1ulJYC9cSWOlNhTNKtCI2koJwh66puvq4gDvV20i+0sOBnUehHUNU3BnZmBkEKJiTBuUGGREUcrBtFIQclw2l8c8id3InQf2l58dXhhlARVuXPfH+s1ET1D38CVV9rATlrqh02MsXPY0HwUcvoTkbc8Sw0IN68ywvtLSjelzW8bUTB46BP1Ae3mlS3HAvBGTSC/iz4bACB4c7VcV3a2EN3LCeXdDuzSr6DUBuzJJ0HIuT7dYF+e8t8Nbdrwp+OhmCPt8cfcqMRIjx4G8fynSyleLQ5vwXh6HRnenfPXKqFz5nWpewoQ4ku/k7AxhELFvK0iswV64s2OVUbxVpPk6ymmK4/jHfRZ/+VtJmIo/PqlgGDz+BlSANu5BBW+k8Ph7hh8BLxg=
