language: node_js
node_js: node
services:
  - mongodb
addons:
  firefox: latest
install:
  - npm install
before_install:
  - "export DISPLAY=:99.0"
  - "export DEBUG=testee:*"
  - "sh -e /etc/init.d/xvfb start"
before_deploy:
  - 'git config --global user.email "mike@bitovi.com"'
  - 'git config --global user.name "Bitcentive Deploy Bot"'
  - node public/build
  - git add public/dist/ --force
  - git commit -m "Updating build."
  - donejs deploy
addons:
  firefox: "latest"
deploy:
  skip_cleanup: true
  provider: heroku
  app: bitcentive
  api_key:
    - secure: >-
        oKXyGYFXcZjbKM+msMYa+0OdgIhnqdbBMcgIdObXnLbtCfwjU0FH0pu85Y4JeU9lebx/mhtOPsVTdksPzGNkFc5dT57cJlaIFklU8IrTSRiUgeuCeYqgKE+TfKRdPQ5vKdLzx470yX7jcIISvzqR+SBFqXFnYuFBUxXNWF1C5gCeqdm6D+LpYxJQ/+VcwZcPk+AwVsnQnqglMQIw7UR5x24gsEU35NRmc9YbHl4f2ASzuG9z9VZgjDdY8vnrJgBNloKE7RC/F4GDnGicdG92ZRAxMg4FQngv85ZsI4JGuy3IhkftCek/hmlV7my4abjO1HJxz4Mu/9Ahqi9PQjMtRInCh039g8jGvw7v/xrTbW6VRFWeh7kjoQb7RSMDmyNJc122rAk1YFx1X8U/Q5FlZs7ikM34y59UNV/iXodKQDkWiaxOicLmBrh+tY9tOBGueFuE+mwJVT9wFEdNuOHKMKO4aCyd7hCPbOx2b2hrf3kCYnC76w37qTx9PHXRAPDNZgT7iuNB3UYYqP8d1lNW4KxZJyqdcnHGjIVpZCYdJj9DO+UdRGn0j64i6OfMHDuGrmcjlK1fh97rU0t3epJsDJmaiRKFTGS2E+kUb++qBKX/tJR5XcbWshIBfPaXF9jyg7zSOvw1AH96MG4jXVW+YfL9GM5eVq4/BhLBXu5s578=
